version: '3.8'

services:
  moodle:
    build: .
    container_name: moodle_app
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./moodledata:/var/www/moodledata
      - ./config.php:/var/www/html/config.php:ro
    environment:
      - MOODLE_URL=http://localhost:8080
      - DB_HOST=postgres
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASSWORD=moodle_password_123
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: moodle_db
    environment:
      - POSTGRES_DB=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_PASSWORD=moodle_password_123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: 